# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftPracticeProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'Firebase/Analytics'
  # Pods for SwiftPracticeProj

# add the Firebase pod for Google Analytics
  pod 'Firebase/Core'
  
# For Example for Firebase Google Login Example
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
